# Generated by Django 6.0.2 on 2026-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_travelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
