# Generated by Django 6.0.2 on 2026-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_travelpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash at Office')], default='upi', max_length=20),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('advance_paid', 'Advance Paid'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelbooking',
            name='traveler_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='payment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='places_included',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='trip_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
